{% set name = "scores" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scores-{{ version }}.tar.gz
  sha256: 1d4e32f33982ca97ff246a92804f235bb33e46fd0b62de5405931d0d634b21ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - xarray >=2024.1,<2025.dev0
    - pandas >=2.2,<3.dev0
    - scipy >=1.1,<2.dev0
    - bottleneck >=1.3,<2.dev0
    - scikit-learn >=1.4,<2.dev0

test:
  imports:
    - scores
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python package for verifying and evaluating models and predictions with xarray
  description: |
     scores is a Python package containing mathematical functions for the verification, evaluation
     and optimisation of forecasts, predictions or models. It supports labelled n-dimensional
     (multidimensional) data, which is used in many scientific fields and in machine learning. At
     present, scores primarily supports the geoscience communities; in particular, the meteorological,
     climatological and oceanographic communities.  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://scores.readthedocs.io/
  home: https://github.com/nci/scores

extra:
  recipe-maintainers:
    - tennlee
