{% set name = "scores" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scores-{{ version }}.tar.gz
  sha256: 7c478abfdcc702b4e03738e3b827f0a8b63652c53176e0295960ca4b9f2b72c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - xarray >=2024.1,<2025.dev0
    - pandas >=2.2,<3.dev0
    - scipy >=1.1,<2.dev0
    - bottleneck >=1.3,<2.dev0
    - scikit-learn >=1.4,<2.dev0

test:
  imports:
    - scores
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scores is a package containing mathematical functions for the verification, evaluation and optimisation of forecasts, predictions or models.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://scores.readthedocs.io/
  home: https://github.com/nci/scores

extra:
  recipe-maintainers:
    - tennlee
